### ISSUE TITLE
Run of bash-game fails with "Cannot find module 'strip-ansi'"

### ISSUE THREAD

**Issue by StephanStS** [fn753/bash-game#1]
After installing the game the start fails with:
```
blabla@fasel:~/bash-game# node main.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'strip-ansi'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/tmp/bash-game/node_modules/prompt-sync/index.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

After installing strip-ansi via `npm install strip-ansi` all works fine.
See also pull request #2.

**Comment by fn753** [comment]
I added the node module strip-ansi into the node_modules folder. Now it should be possible to start the game without installing the module.
